### ISSUE TITLE
sas.df2sas() method call does not trap missing libref

### ISSUE THREAD

**Issue by RandyBetancourt** [sassoftware/saspy#205]
Hi Guys,

Running saspy 2.3.0 on Windows 10 with a winlocal configuration.   

Calling the sas.df2sd() method when a SAS Libref is not defined does not trap the missing Libref in the Python session (which is running in a Jupyter notebook).  Of course, the remedy is to call the sas.saslib() method to defining the Libref prior to calling the sas.df2sd() method.

A 'nice-to-have' is an error message returned to the notebook before having to search the SAS log.  

    import pandas as pd
    import saspy
    data = {'col1': [1, 2], 'col2': [3, 4]}
    df = pd.DataFrame(data=data)
    sas_ds = sas.df2sd(df, table='test_data', libref='sas_data')
    print(sas.saslog())

from the SAS log:

    23         data sas_data.test_data;
    24         length  'col1'n 8 'col2'n 8;
    25         infile datalines delimiter='03'x DSD STOPOVER;
    26         input @;
    27         if _infile_ = '' then delete;
    28         input 'col1'n 'col2'n ;
    29         datalines4;

ERROR: Libref SAS_DATA is not assigned.

<img width="815" alt="capture1" src="https://user-images.githubusercontent.com/22532833/50611324-ed960200-0ea3-11e9-89e1-b46fe5aa64bd.PNG">

Best regards,
Randy

**Comment by tomweber-sas** [comment]
Hey Randy, thanks, I'll clean that up!

**Comment by tomweber-sas** [comment]
@RandyBetancourt I just pushed this fix to master. Can you pull that and give it a try. Worked well for all the cases I had. Let's make sure it's working for you the same.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey @RandyBetancourt !  Have you had a chance to verify this fix for your case? If all's well, we can close this issue?
Thanks,
Tom

**Comment by RandyBetancourt** [comment]
Hi Tom,

Thanks for the reminder.  I did:
$ python -m pip install -U saspy

and was returned:

Successfully built saspy
Installing collected packages: saspy
  Found existing installation: saspy 2.3.0
    Uninstalling saspy-2.3.0:
      Successfully uninstalled saspy-2.3.0
Successfully installed saspy-2.4.1

Still getting the same results:

<img width="944" alt="capture" src="https://user-images.githubusercontent.com/22532833/52495584-2742e280-2b9f-11e9-9a4d-fc21d1688a67.PNG">

Or, do I need another pip command to pick-up these changes?

Best regards,
Randy

**Comment by tomweber-sas** [comment]
Yeah Randy, it's at master not out in a pip package. So to pull master, just use this instead:
```
pip install git+https://git@github.com/sassoftware/saspy.git
```
Thanks!
Tom

**Comment by RandyBetancourt** [comment]
huh, for some reason, I not able to pick up the change.  I ran the git command.  I started a new command window and then launched python with the saspy script.

git says:

$ python -m pip install git+https://git@github.com/sassoftware/saspy.git                                                                                                                                   Collecting git+https://git@github.com/sassoftware/saspy.git                                                                                                                                                  Cloning https://git@github.com/sassoftware/saspy.git to c:\users\randy\appdata                                                                                                                           \local\temp\pip-req-build-7wodqypg                                                                                                                                                                         Requirement already satisfied (use --upgrade to upgrade): saspy==2.4.1 from git+                                                                                                                           https://git@github.com/sassoftware/saspy.git in c:\users\randy\anaconda3\lib\sit                                                                                                                           e-packages                                                                                                                                                                                                 Requirement already satisfied: pygments in c:\users\randy\anaconda3\lib\site-pac                                                                                                                           kages (from saspy==2.4.1) (2.2.0)                                                                                                                                                                          Requirement already satisfied: ipython>=4.0.0 in c:\users\randy\anaconda3\lib\si                                                                                                                           te-packages (from saspy==2.4.1) (6.4.0)                                                                                                                                                                    Requirement already satisfied: decorator in c:\users\randy\anaconda3\lib\site-pa                                                                                                                           ckages (from ipython>=4.0.0->saspy==2.4.1) (4.3.0)                                                                                                                                                         Requirement already satisfied: setuptools>=18.5 in c:\users\randy\anaconda3\lib\                                                                                                                           site-packages (from ipython>=4.0.0->saspy==2.4.1) (39.1.0)                                                                                                                                                 Requirement already satisfied: simplegeneric>0.8 in c:\users\randy\anaconda3\lib                                                                                                                           \site-packages (from ipython>=4.0.0->saspy==2.4.1) (0.8.1)                                                                                                                                                 Requirement already satisfied: pickleshare in c:\users\randy\anaconda3\lib\site-                                                                                                                           packages (from ipython>=4.0.0->saspy==2.4.1) (0.7.4)                                                                                                                                                       Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.15 in c:\users\randy\a                                                                                                                           naconda3\lib\site-packages (from ipython>=4.0.0->saspy==2.4.1) (1.0.15)                                                                                                                                    Requirement already satisfied: backcall in c:\users\randy\anaconda3\lib\site-pac                                                                                                                           kages (from ipython>=4.0.0->saspy==2.4.1) (0.1.0)                                                                                                                                                          Requirement already satisfied: traitlets>=4.2 in c:\users\randy\anaconda3\lib\si                                                                                                                           te-packages (from ipython>=4.0.0->saspy==2.4.1) (4.3.2)                                                                                                                                                    Requirement already satisfied: jedi>=0.10 in c:\users\randy\anaconda3\lib\site-p                                                                                                                           ackages (from ipython>=4.0.0->saspy==2.4.1) (0.12.0)                                                                                                                                                       Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\ran                                                                                                                           dy\anaconda3\lib\site-packages (from ipython>=4.0.0->saspy==2.4.1) (0.3.9)                                                                                                                                 Requirement already satisfied: six>=1.9.0 in c:\users\randy\anaconda3\lib\site-p                                                                                                                           ackages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=4.0.0->saspy==2.4.1) (1.11                                                                                                                           .0)                                                                                                                                                                                                        Requirement already satisfied: wcwidth in c:\users\randy\anaconda3\lib\site-pack                                                                                                                           ages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=4.0.0->saspy==2.4.1) (0.1.7)                                                                                                                            Requirement already satisfied: ipython_genutils in c:\users\randy\anaconda3\lib\                                                                                                                           site-packages (from traitlets>=4.2->ipython>=4.0.0->saspy==2.4.1) (0.2.0)                                                                                                                                  Requirement already satisfied: parso>=0.2.0 in c:\users\randy\anaconda3\lib\site                                                                                                                           -packages (from jedi>=0.10->ipython>=4.0.0->saspy==2.4.1) (0.2.0)                                                                                                                                          Building wheels for collected packages: saspy                                                                                                                                                                Running setup.py bdist_wheel for saspy: started                                                                                                                                                            Running setup.py bdist_wheel for saspy: finished with status 'done'                                                                                                                                        Stored in directory: C:\Users\randy\AppData\Local\Temp\pip-ephem-wheel-cache-w                                                                                                                           fw1qvnu\wheels\60\a5\77\46d09cd0140facbc1e748cd984a8ab399ca467b6c425095db1                                                                                                                                 Successfully built saspy                                                                                                                                                                                   You are using pip version 18.1, however version 19.0.1 is available.                                                                                                                                       You should consider upgrading via the 'python -m pip install --upgrade pip' comm                                                                                                                           and.
--
It seems to me there is no change to the saspy module for the git command
I start a new terminal window and the new python session returns:

>>> import pandas as pd
>>> import saspy
>>>
>>> sas = saspy.SASsession(cfgname='winlocal', results='HTML')
SAS Connection established. Subprocess id is 17948

>>> saspy.__version__
'2.4.1'
>>>
>>> data = {'col1' : [1, 2], 'col2' : [3, 4]}
>>> df = pd.DataFrame(data = data)
>>>
>>> sas_ds = sas.df2sd(df, table = 'test_data', libref = 'sas_data')
>>>
>>> print(sas.saslog())
1                                                          The SAS System                             14:22 Friday, February 8, 2019

NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M5)
      Licensed to STRONG TOWER SOLUTIONS INC, Site 70114891.
NOTE: This session is executing on the X64_10PRO  platform.



NOTE: Updated analytical products:

      SAS/STAT 14.3

NOTE: Additional host information:

 X64_10PRO WIN 10.0.17134  Workstation

NOTE: SAS Initialization used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds

1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any pagesize=max nosyntaxcheck; ods graphics on;
3
4          ;*';*";*/;
5          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
6
2                                                          The SAS System                             14:22 Friday, February 8, 2019

7          ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
7        ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
8          ;*';*";*/;
9
10                             %put WORKPATH=%sysfunc(pathname(work));
WORKPATH=C:\Users\randy\AppData\Local\Temp\SAS Temporary Files\_TD24304_RANDY-PC_\Prc2
11                             %put ENCODING=&SYSENCODING;
ENCODING=wlatin1
12                             %put SYSVLONG=&SYSVLONG4;
SYSVLONG=9.04.01M5P09132017
13                             %put SYSJOBID=&SYSJOBID;
SYSJOBID=24304
14                             %put SYSSCP=&SYSSCP;
SYSSCP=WIN
15
16
17         ;*';*";*/;ods html5 (id=saspy_internal) close;ods listing;
18
19         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
20
3                                                          The SAS System                             14:22 Friday, February 8, 2019

21         data sas_data.test_data;
22         length  'col1'n 8 'col2'n 8;
23         infile datalines delimiter='03'x DSD STOPOVER;
24         input @;
25         if _infile_ = '' then delete;
26         input 'col1'n 'col2'n ;
27         datalines4;

ERROR: Libref SAS_DATA is not assigned.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds

4                                                          The SAS System                             14:22 Friday, February 8, 2019

31         ;;;;


32         run;
33
5                                                          The SAS System                             14:22 Friday, February 8, 2019

34         ;*';*";*/;
35
36
37         ;*';*";*/;
38         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
39
6                                                          The SAS System                             14:22 Friday, February 8, 2019

40         ;*';*";*/;
41         data _null_; e = exist('sas_data.test_data');
42         v = exist('sas_data.test_data', 'VIEW');
43          if e or v then e = 1;
44         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


45
46
47         ;*';*";*/;
48         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
49

>>> sas.assigned_librefs()
['WORK', 'SASHELP', 'SASUSER']
>>>

Of course,  the assigned_librefs() method doesn't know about the attempt to call the sas_data libref.

**Comment by tomweber-sas** [comment]
Oh, I suspect that's because the version number hasn't been bumped up at master, so it won't do anything. if you uninstall first, it will then download and install what's at master.
```
pip uninstall saspy
pip install git+https://git@github.com/sassoftware/saspy.git
```

**Comment by RandyBetancourt** [comment]
got it.  Thanks for that.  Please close the issue.

>>> sas_ds = sas.df2sd(df, table = 'test_data', libref = 'sas_data')
The libref specified is not assigned in this SAS Session.

**Comment by tomweber-sas** [comment]
will do. Thanks for verifying!
Thanks,
Tom
