### ISSUE TITLE
columns with missing values become dataframe objects instead of dataframe float64 NaN

### ISSUE THREAD

**Issue by windpeterson** [sassoftware/saspy#347]
**Describe the bug**
If I have a table with a single row, and one of the columns in the table is numeric but has a missing value, when I use the sd2df method that column is of type object rather than type float64 in the resulting dataframe. This creates issues when bringing data back into SAS, as using df2sd on the dataframe and then inserting the data into the table it was taken from results in a type error, because the object column is treated as character rather than as numeric.

**To Reproduce**
1. Create a table in SAS that has a numeric data type but a missing value.
2. Use sd2df method to create a DataFrame from the SAS data.
3. Check the DataFrames dtypes. The column with the missing value will have an object dtype.

import pandas as pd
import saspy

code = """data weight2;  
   infile datalines missover;
   input IDnumber $ Week1 Week16;  
   WeightLoss2=Week1-Week16;
   datalines;
2431 173
;             
run;"""

sas = saspy.SASsession()
sas.submitLOG(code)
data = pd.DataFrame()
data = sas.sd2df(table='weight2', libref='work')
print(data.dtypes)

![image](https://user-images.githubusercontent.com/66880107/100931154-c2f9bd00-34af-11eb-85f4-5637a0d35554.png)

**Expected behavior**
Numeric columns with missing values should have float64 dtype and NaN value.

**Desktop (please complete the following information):**
 - OS: Windows
 - SAS Version: 9.04.01M
 - SASPy Version: 3.3.7

**Additional context**
IOM using COM connection method

**Comment by tomweber-sas** [comment]
Really? Well that's not right! You know, that sounds familiar, and I think I may have introduced that with a bunch of enhancements for sd2df a while back. Then I fixed something like that. Yes, I'll go track this down instead of just saying what I think I remember :), but I wonder if you get a more recent version, if that's already fixed?

I'll go see when, what I think I remember, was done. It may be back in the version you have. If you can try the current version, without any trouble, that's be great.

But, I'll go see if I can reproduce this too, with your version and the current and see if it's still an issue.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Oh, I just noticed you're using COM. Then, what I was remembering isn't about that anyway. That was with the access methods I wrote. COM is a user contributed one and it doesn't have exactly all the same behaviors as mine. I'll look at that to see if it's something I may be able to do something about or not. So, I double the current saspy would change the behavior. 
Since you're using widows, can you try the IOM access method to see if it already works like you expect? All you need is java available, and the current version of saspy already has the jars and things you used to have to configure, already handled for you (it's a lot easier to configure that it used to be). Is installing the current saspy and trying IOM something you can do?

I'll still look at COM to see if this is something I can fix, but IOM is your real best choice.

Thanks,
Tom

**Comment by windpeterson** [comment]
The issue is present in SASPy Version: 3.6.1 as well.

Unfortunately, in my use case COM is the only connection method I am able to use with SASPy.

**Comment by tomweber-sas** [comment]
I probably should have actually ran your code before assuming I had any possible answers :) So sorry for the noise

The code you provided creates a CHAR column, because of your SAS code, so the dataframe having object (which is what SAS CHAR is, in the data  frame), is correct. It has nothing to do with either access method (not the issue I was thinking of).

If you created that column in SAS as NUM instead of CHAR, it would have been numeric in the data frame.
Here's the results:
```

tom64-5> python3.5
]Python 3.5.6 (default, Nov 16 2018, 15:50:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import saspy
>>>
>>> code = """data weight2;
... infile datalines missover;
... input IDnumber $ Week1 Week16;
... WeightLoss2=Week1-Week16;
... datalines;
... 2431 173
... ;
... run;"""
>>>
>>> sas = saspy.SASsession()
Please enter the name of the SAS Config you wish to run. Available Configs are: ['default', 'SASgrid', 'http', 'httptest', 'ssh', 'sshtun', 'sshrtun', 'httpfred', 'grid', 'tdi', 'tdi_cn', 'tdi_cn8', 'tdilat', 'oda', 'iomj', 'sdssas_cn', 'sdssas_u8', 'iomc', 'iomjwin', 'winiomj', 'winiomjwin', 'winlocal', 'gridiom', 'wingridiom', 'zos', 'zos2', 'winzos', 'winzos2', 'sshtest', 'sshloc', 'sdssas', 'saskr', 'vb010', 'vb015', 'pune', 'notpune', 'iomkr', 'httpviya', 'kevin', 'issue176', 'httpjason', 'itviya', 'carrie1', 'console', 'iomcom', 'iomcom_loc', 'iom4', 'm5bug', 'spre34', 'sshprob', 'vbviya', 'vbviyaxx', 'vbviyapp', 'alex', 'dotat', 'dotav', 'dotap', 'odadev', 'mahesh', 'viya_cn']  iomj
SAS Connection established. Subprocess id is 29385

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to utf_8 based upon the SAS session encoding value of utf-8.

>>> sas
Access Method         = IOM
SAS Config name       = iomj
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_workAF7E00006687_tom64-5/SAS_work022400006687_tom64-5/
SAS Version           = 9.04.01M4D11092016
SASPy Version         = 3.6.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 26247


>>> sas.submitLOG(code)
7                                                          The SAS System                          16:33 Wednesday, December 2, 2020

34         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
34       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
35
36         data weight2;
37         infile datalines missover;
38         input IDnumber $ Week1 Week16;
39         WeightLoss2=Week1-Week16;
40         datalines;

NOTE: Missing values were generated as a result of performing an operation on missing values.
      Each place is given by: (Number of times) at (Line):(Column).
      1 at 39:18
NOTE: The data set WORK.WEIGHT2 has 1 observations and 4 variables.
NOTE: DATA statement used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds


42         ;
1                                                          The SAS System                          16:33 Wednesday, December 2, 2020

NOTE: html5 Memory Usage (274 events)
      Total: 2.79MB     High: 1283.89KB     Max: 32807B     Allocs: 16838   Frees: 16838
43         run;
44
45
46         ods html5 (id=saspy_internal) close;ods listing;
47
8                                                          The SAS System                          16:33 Wednesday, December 2, 2020

48
>>> weight = sas.sasdata('weight2')
>>> weight
Libref  = WORK
Table   = weight2
Dsopts  = {}
Results = Pandas

>>> weight.columnInfo()
         Member  Num     Variable  Type  Len  Pos
0  WORK.WEIGHT2    1     IDnumber  Char    8   24
1  WORK.WEIGHT2    2        Week1   Num    8    0
2  WORK.WEIGHT2    3       Week16   Num    8    8
3  WORK.WEIGHT2    4  WeightLoss2   Num    8   16
>>> data = sas.sd2df(table='weight2', libref='work')
>>> data2 = weight.to_df()
>>> data.dtypes
IDnumber        object
Week1            int64
Week16         float64
WeightLoss2    float64
dtype: object
>>> data2.dtypes
IDnumber        object
Week1            int64
Week16         float64
WeightLoss2    float64
dtype: object
>>>
```
Now create a numeric type in SAS (delete the $, which made the variable a char, and it will default to NUM):
```

>>>
>>> code = """data weight2;
... infile datalines missover;
... input IDnumber Week1 Week16;
... WeightLoss2=Week1-Week16;
... datalines;
... 2431 173
... ;
... run;"""
>>> sas.submitLOG(code)
46                                                         The SAS System                          16:33 Wednesday, December 2, 2020

283        ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
283      ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
284
285        data weight2;
286        infile datalines missover;
287        input IDnumber Week1 Week16;
288        WeightLoss2=Week1-Week16;
289        datalines;

NOTE: Missing values were generated as a result of performing an operation on missing values.
      Each place is given by: (Number of times) at (Line):(Column).
      1 at 288:18
NOTE: The data set WORK.WEIGHT2 has 1 observations and 4 variables.
NOTE: DATA statement used (Total process time):
      real time           0.04 seconds
      cpu time            0.03 seconds


291        ;
1                                                          The SAS System                          16:39 Wednesday, December 2, 2020

NOTE: html5 Memory Usage (274 events)
      Total: 2.79MB     High: 1283.89KB     Max: 32807B     Allocs: 16838   Frees: 16838
292        run;
293
294
295        ods html5 (id=saspy_internal) close;ods listing;
296
47                                                         The SAS System                          16:33 Wednesday, December 2, 2020

297
>>> weight.columnInfo()
         Member  Num     Variable Type  Len  Pos
0  WORK.WEIGHT2    1     IDnumber  Num    8    0
1  WORK.WEIGHT2    2        Week1  Num    8    8
2  WORK.WEIGHT2    3       Week16  Num    8   16
3  WORK.WEIGHT2    4  WeightLoss2  Num    8   24
>>> data2 = weight.to_df()
>>> data2.dtypes
IDnumber         int64
Week1            int64
Week16         float64
WeightLoss2    float64
dtype: object
>>>
```

**Comment by windpeterson** [comment]
The issues for me are the columns with the missing values, Week16 and WeightLoss2. 

Removing the character element, I still have an issue when using the IOM over COM connection type:

![image](https://user-images.githubusercontent.com/66880107/100935752-1c64ea80-34b6-11eb-85e3-98b2066f1ece.png)

**Comment by tomweber-sas** [comment]
Wow, I am way off today!   So forget that last one, I was looking at the wrong column! Cripes!
I ran it with IOM which did as I expect, so the only column that was object (CHAR) was that first one, which sent me down that last thread (WRONG). I ran the code w/COM and saw the wrong types for the last 2 columns!

So, I'll go back to seeing if there's anything I can do for the COM access method to try to fix this.

Out of curiosity, why can't you use IOM instead of COM in this case? But, regardless, I'll see if I cna figure out is I can do something in the COM access method to address this. As a workaround, you can simply change the type after, if that helps at all:
```
data['WeightLoss2'] = data['WeightLoss2'].astype('float64')
data.dtypes 
IDnumber       float64
Week1          float64
Week16          object
WeightLoss2    float64
dtype: object
```

**Comment by tomweber-sas** [comment]
Hey, I also just tried using the CSV method, in COM and it created the correct types. 
```
data = sas.sd2df_CSV(table='weight2', libref='work')
data.dtypes
IDnumber         int64
Week1            int64
Week16         float64
WeightLoss2    float64
dtype: object
```

So that's something else you can use now to get the corrrect types, if that works for your use case. 

I'll still look at the MEMORY version which doesn't get you the correct types to see if there's anything I can do to fix that.

**Comment by tomweber-sas** [comment]
I see what needs to happen, and I've actually put a fix in that works. But I have to research this more to know it's a correct fix. If you want to try it out, you can edit your copy of sasiocom.py in your saspy install and add 2 lines to the end of the sasdata2dataframe method (line 774 in v3.6.1)

```
               elif meta[col]['DATA_TYPE'] == 5:
                  df[col] = pd.to_numeric(df[col], errors='coerce')
```

So you should see the following with these two lines (context lines above and below):
```

            header, rows, meta = self.read_sasdata(table, libref, dsopts=dsopts)
            df = pd.DataFrame.from_records(rows, columns=header, **kwargs)

            for col in meta.keys():
               if meta[col]['FORMAT_NAME'] in self._sb.sas_date_fmts + self._sb.sas_datetime_fmts: 
                  df[col] = pd.to_datetime(df[col], errors='coerce')
               elif meta[col]['DATA_TYPE'] == 5:
                  df[col] = pd.to_numeric(df[col], errors='coerce')

        return df

    def sasdata2dataframeCSV(self, table: str, libref: str ='', dsopts: dict = None, 
                             tempfile: str=None, tempkeep: bool=False, **kwargs) -> 'pd.DataFrame':
```

If you feel comfortable tweaking your code, add those 2 lines and see if it behaves as you expect. I'll have to research what this metadata is and what the possibilities are for the DATA_TYPE, so I know that this is really right or not, or how to make sure it is. But, it seems straight forward enough that it's probably the right answer. Hopefully this works for all of your cases.

I'll see about getting this figured out for sure and pushed out to main tomorrow so you can try it from there also.

Sorry for the confusion to begin with, but it looks like I can provide you a real fix tomorrow!
Tom

**Comment by windpeterson** [comment]
Use case is a GUI that will be compiled to an .exe. Thank you for the quick response!

**Comment by tomweber-sas** [comment]
Hey, that sounds pretty cool! So, I can't find any doc about the internals of this third party module the COM access method used to transfer data; win32com and adodb and the query stuff it uses, ...   But, empirically, the metadata it gets for the columns seems to simply be 130 or 5 as the data type; SAS only has float and char (well, fixed length byte array, but, that's what contains chars), so those are really the only two values that come back in the data type field of all this metadata. And, as we're only looking for the numeric (data type = 5; char is the 130), this 2 line fix appears solid to me.

I've gone ahead and pushed it to the main branch, though it's not been built into a version yet. So it's not on Pypi yet. Can you pull from main, or just add those 2 lines (that's what I pushed) and versify this solves your cases?
```
pip uninstall -y saspy
pip install git+https://git@github.com/sassoftware/saspy.git
```

Thanks,
Tom

**Comment by windpeterson** [comment]
I tested the change and have verified that this solves my issues. Thank you for the help!

**Comment by tomweber-sas** [comment]
Awesome! I should be building a new version within the next few days, if that matters to you. It'll just be what's at main, so you have the code now anyway. But is will be the official version 3.6.2 once that's done.
Again, sorry for all of the confusion to start with yesterday; was an off day for me :)
